### ISSUE TITLE
Can you tell me what theory this code is based on?

### ISSUE THREAD

**Issue by Liber-coder** [jac14700/MSRCR_Real-time-on-Opencv#1]
Hello! I ran your code and it looks good!

But I can't understand `SimplestCB()` and this line of code: `log_Retinex[i] = log_Retinex[i]*(log10(125*frame.at<Vec3b>(y,x)[i])-log10(frame.at<Vec3b>(y,x)[0]+frame.at<Vec3b>(y,x)[1]+frame.at<Vec3b>(y,x)[2]));`

Can you tell me what theory this code is based on?

By the way, I deleted this line of code: `log_Retinex[i] = log_Retinex[i]*(log10(125*frame.at<Vec3b>(y,x)[i])-log10(frame.at<Vec3b>(y,x)[0]+frame.at<Vec3b>(y,x)[1]+frame.at<Vec3b>(y,x)[2]));`, and the color seems to be improved.

**Comment by jac14700** [comment]
@KNLc The code you find here is basically based on those papers in the following website .https://github.com/jac14700/MSRCR/tree/master/Theory, 
For the code you delete, I believe it is for retinex, if you have a better result by deleting it, you can just remove it, it depends ! :D
BTW,  I'm sorry for the late response
